name: Build Result

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches: [master]
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Download repository code
        uses: actions/checkout@v7

      - name: Build Result image
        run: docker build --progress=plain -t voting-vote:test ./vote

      - name: Verify image exists
        run: docker image inspect voting-vote:test
